CREATE TABLE users (
	userid INTEGER NOT NULL PRIMARY KEY,
	username VARCHAR(64) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	signup_ip VARCHAR(64) NOT NULL DEFAULT '',
	signup_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE links (
	linkid INTEGER NOT NULL PRIMARY KEY,
	userid INTEGER NOT NULL,
	name VARCHAR(255) NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT '',
	shortname VARCHAR(255) UNIQUE,
	url TEXT NOT NULL,
	added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	accessed DATETIME,
	CONSTRAINT user_url_unique UNIQUE (userid, url) ON CONFLICT FAIL
);
